language: node_js
install: npm ci
jobs:
  include:
  - stage: Lint JS
    script:
    - npm run lint
    - npm run test
deploy:
  provider: heroku
  app: discord-bot-test-btaniguchi
  api_key:
    secure: v6QZXII98//1xLRsVVqPm0x1NnU2+UtCZNLJVGGmU3TE4TAEgGPBBxV7TzOQ9it4Z/wPloomUzKpZotcHlJD1WvBJMJFF4IP1DUSCxmJW/bpaxxXCeDTShJSv+KvziPAwVMJw7URKEO3Jnxs2mwyMFKUW0op1q05OfIRsGfDiMzwQbm+q3IdWhgMof7U/RVGrArRRN45Z14blEkSS221mQf4MM62AG0fuV3SmXLS8uGYnUd/SggOoajgj79oMTp2xIPK97CndnTfL0bH9f3RozV3OM4MQj8uPGXBApAHEkBbxFobfoVZCjv0WOLjsnU87IMOH/oaZs2tjvvAfpFE9b4Bk9WKPVlwkhPSR3r3gHcIQOPOXMRvQPcXlSdcXCtjFBJ7OEk3kRlk3ogG6BEmaQJH9SbUvN68xyRPy9D4KseIMVWBOXShR2a4IB5jWS2x7/nFMAiZiQHiwdpfGhH0f1+SmWlzZFxJBIMJnUgnHjIdJ9jUuuah0z/3AZznoDzsY+5/1KIYw2P2FeTW4exdmLJQ9aNYnrF1xume70Q7PnJqWFxiJidkKtWABsjILpeR1LrHD5Yc6jt9jWP67XjZd4G+ulLYyNR8tyi/pLjuR4LQFz9DoGZ6gvs+fIXJHi1rAd/2Z/N+M2hTTBLRq18h+Ak1JbxLoQF0mdiIefpimuU=
