language: node_js
install: npm ci
jobs:
  include:
  - stage: Lint JS
    script:
    - npm run lint
    - npm run test
deploy:
  provider: heroku
  app: discord-bot-test-btaniguchi
  api_key:
    secure: DHL1ICmJY3WH1x0l18I8kwE459OZB9JwonkCEsatKosrm4iJumOsAf6H4m3V3WzrEYcotYF+gLPaxXYIFyYuGMK1naUPbTNc+ZEFnQL/idX4Hv87ZDWcMTPrgTwiahUR/yGqyUO65iU9f1bQ81f9POpJK1Atx5ouD1/jiBnUMkfRhf9GvOWTGl1bq1g5FYUV2UTzDq/fi7+QVJj/wt9xEcdYFBMoruqEipsNDD3wywY2qUiU0JRlRMp/5N/gXr8gptRMGzKP5OqrAk0/kMC+x5az4Pq4Sj9q98VjvhUTvP+QPIvh10yp7vqawxGTsoUWuTf1PZWyN89tujubB3FGryH7nWGMpV5iloex4Zv/sUmwT63zBphjXudIDoFemFFxVVrKRlVer6KB1fgyAl/XXLgFI9zAB+HQTswiObRrbr+KsH9AJ4jgOQa525zYT5KfQAzPsYvTuZWsnapzhrdcuqvE0B41sZKVEjEA6OMnh2LB5luiGrn01ZEFFDNr15a2iVeR9+J2lvada5bYR2voke7lYpvrmMSTedffcWBEtghHY7FYcUao1yxpvZ3v1o9Pl15nyPZdScIvq5ceQQF/7HYkcG8rvyhDRSAf7nCp6/WXrrHiRZf3OXAfwaJEOE06YO7mmVepn5qY+XuXoNVIlbXzWVgFiOys209mFLZh7mk=
